<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class=\"img-responsive\" ><img src='{@me['litpic']}'/></a>\"); ",166,328);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",506,523);
$z[1][4]=array();
$z[2]=Array("arcurl","",538,553);
$z[2][4]=array();
$z[3]=Array("title","",569,583);
$z[3][4]=array();
$z[4]=Array("description","",646,666);
$z[4][4]=array();

?>