<div class="row" id="list-item">
                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" id="listImg">
                                    [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img class="img-responsive" src='{@me['litpic']}' /></a>"); [/field:array] 
                                </div>
                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" id="listright"> 
                                [<b>[field:typelink/]</b>] <a href="[field:arcurl/]" class="title">[field:title/]</a> <span class="info"> 
                                <p> [field:description/]... </p>  
                                </div>
                             </div>