<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' class=\"img-responsive\"/></a>\"); ",166,343);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",521,538);
$z[1][4]=array();
$z[2]=Array("arcurl","",553,568);
$z[2][4]=array();
$z[3]=Array("title","",584,598);
$z[3][4]=array();
$z[4]=Array("description","",661,681);
$z[4][4]=array();

?>