<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",146,300);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",465,482);
$z[1][4]=array();
$z[2]=Array("arcurl","",497,512);
$z[2][4]=array();
$z[3]=Array("title","",528,542);
$z[3][4]=array();
$z[4]=Array("description","",604,624);
$z[4][4]=array();

?>