<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",151,305);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",483,500);
$z[1][4]=array();
$z[2]=Array("arcurl","",515,530);
$z[2][4]=array();
$z[3]=Array("title","",546,560);
$z[3][4]=array();
$z[4]=Array("description","",623,643);
$z[4][4]=array();

?>