<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' class=\"img-responsive\" /></a>\"); ",166,344);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",522,539);
$z[1][4]=array();
$z[2]=Array("arcurl","",554,569);
$z[2][4]=array();
$z[3]=Array("title","",585,599);
$z[3][4]=array();
$z[4]=Array("description","",662,682);
$z[4][4]=array();

?>