<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",166,320);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",498,515);
$z[1][4]=array();
$z[2]=Array("arcurl","",530,545);
$z[2][4]=array();
$z[3]=Array("title","",561,575);
$z[3][4]=array();
$z[4]=Array("description","",655,675);
$z[4][4]=array();

?>