<li>
                                <div>
                                    <time>[field:title/]</time>
                                    <div class="discovery">
                                        <h1>Discovery</h1>
                                        <p>
                                            Laws of motion
                                        </p>
                                    </div>
                                    <div class="scientist">
                                        <h1>Scientist</h1>
                                        <span>Newton</span>
                                    </div>
                                </div>
                            </li>