<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='img-responsive'><img src='{@me['litpic']}'/></a>\"); ",166,327);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",505,522);
$z[1][4]=array();
$z[2]=Array("arcurl","",537,552);
$z[2][4]=array();
$z[3]=Array("title","",568,582);
$z[3][4]=array();
$z[4]=Array("description","",645,665);
$z[4][4]=array();

?>