<li class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <div class="wrap">              
										<h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
										<p>[field:description/]...</p>
										<span>	
										  <small>分类：</small><a href="[field:typeurl/]" target="_blank">[field:typename/]</a>
										  <small>点击：</small>[field:click/]
										  <small>日期：</small>[field:stime/]
                                        </span>
                                        </div>
									  </li>