<li>
                                <div>
                                    <time>[field:title/]</time>
                                    <div class="maskImg">
                                      [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array] 
                                    </div>
                                      
                                </div>
                            </li>