<?php
$z[0]=Array("global","",601,633);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1046,1074);
$z[1][4]=array();
$z[1][4]['name']="cfg_memberurl";
$z[2]=Array("global","",2019,2047);
$z[2][4]=array();
$z[2][4]['name']="cfg_memberurl";
$z[3]=Array("memberlist","\r\n   <li><a href=\"[field:spaceurl/]\" target=\"_blank\"><img src=\"[field:face/]\" alt='[field:spacename/]' width=\"52\" height=\"52\" />[field:uname/]</a></li>\r\n   ",3364,3572);
$z[3][4]=array();
$z[3][4]['row']="6";
$z[3][4]['signlen']="30";

?>