<?php
$z[0]=Array("global","",217,243);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",2146,2181);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",2397,2429);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",2710,2739);
$z[3][4]=array();
$z[3][4]['name']="position";
$z[4]=Array("sql","\r\n                                        [field:body function='cn_substr(html2text(@me),10000)'/]\r\n                                        ",3920,4139);
$z[4][4]=array();
$z[4][4]['sql']="SELECT body FROM `dede_addonarticle` where aid = 44";
$z[5]=Array("sql","\r\n                                        [field:body function='cn_substr(html2text(@me),10000)'/]\r\n                                        ",4435,4654);
$z[5][4]=array();
$z[5][4]['sql']="SELECT body FROM `dede_addonarticle` where aid = 45";
$z[6]=Array("sql","\r\n                                        [field:body function='cn_substr(html2text(@me),10000)'/]\r\n                                        ",4950,5169);
$z[6][4]=array();
$z[6][4]['sql']="SELECT body FROM `dede_addonarticle` where aid = 46";
$z[7]=Array("sql","\r\n                                        [field:body function='cn_substr(html2text(@me),10000)'/]\r\n                                        ",5465,5684);
$z[7][4]=array();
$z[7][4]['sql']="SELECT body FROM `dede_addonarticle` where aid = 47";
$z[8]=Array("sql","\r\n                                        [field:body function='cn_substr(html2text(@me),10000)'/]\r\n                                        ",5980,6199);
$z[8][4]=array();
$z[8][4]['sql']="SELECT body FROM `dede_addonarticle` where aid = 48";
$z[9]=Array("include","",6897,6934);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>