<?php
$z[0]=Array("global","",217,243);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",2702,2737);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",2952,2984);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",3253,3282);
$z[3][4]=array();
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n                <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n                        <div class=\"imglist\">\r\n                        <p class=\"text-center\"><a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a></p>\r\n                        [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic'] }' /></a>\"); [/field:array] \r\n                       </div>\r\n                </div> \r\n                ",3375,3895);
$z[4][4]=array();
$z[4][4]['pagesize']="12";
$z[5]=Array("pagelist","",4034,4100);
$z[5][4]=array();
$z[5][4]['listitem']="index,end,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",4690,4727);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>