<?php
$z[0]=Array("global","",217,243);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",5590,5625);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",5836,5868);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",6138,6167);
$z[3][4]=array();
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n                            <li>\r\n                                <div>\r\n                                    <time>[field:title/]</time>\r\n                                    <div class=\"maskImg\">\r\n                                      [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); [/field:array] \r\n                                    </div>\r\n                                      \r\n                                </div>\r\n                            </li>  \r\n                            ",6327,6946);
$z[4][4]=array();
$z[4][4]['pagesize']="8";
$z[5]=Array("include","",7575,7612);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>